# Generated by Django 4.2.5 on 2023-09-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saep_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma_atividade',
            name='fk_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saep_app.atividade'),
        ),
    ]
